--[[

▇▇▇                                       ▇▇▇               
▇▇        ▇                        ▇       ▇▇             
▇▇          ▇ @KGT_dady   ▇         ▇▇            
▇▇             ▇             ▇             ▇▇        Dev : MOHAMED BAKKAR
▇▇                ▇       ▇                ▇▇      
▇▇                   ▇▇                    ▇▇     Source revor BY @KGT_dady
#-------------------------------------------------------------------
]]

local function dadya(msg,MsgText)
if msg.type ~= "pv" then
if MsgText[1] == "زخرفه" then
redis:setex(dady..":dadyNow:"..msg.sender_user_id_,500,true)
sendMsg(msg.chat_id_,msg.id_,"| حسننا , الان يمكنك ارسال الاسم ولبعض الرموز المميزه اكتب رموز")    
return false
end

if redis:get(dady..":dadyNow:"..msg.sender_user_id_) then
redis:del(dady..":dadyNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكنك زخرفه اكثر من 20 حرف \n| ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
elseif msg.text:match("\n") then
sendMsg(msg.chat_id_,msg.id_,"| لا يمكن زخرفه نص يحتوي على اكثر من سطر .")
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local dady = Text:gsub('ض','ضِٰـِۢ')
dady = dady:gsub('ص','صِٰـِۢ')
dady = dady:gsub('ث','ثِٰـِۢ')
dady = dady:gsub('ق','قِٰـِۢ')
dady = dady:gsub('ف','فِٰ͒ـِۢ')
dady = dady:gsub('غ','غِٰـِۢ')
dady = dady:gsub('ع','عِٰـِۢ')
dady = dady:gsub('خ','خِٰ̐ـِۢ')
dady = dady:gsub('ح','حِٰـِۢ')
dady = dady:gsub('ج','جِٰـِۢ')
dady = dady:gsub('ش','شِٰـِۢ')
dady = dady:gsub('س','سِٰـِۢ')
dady = dady:gsub('ي','يِٰـِۢ')
dady = dady:gsub('ب','بِٰـِۢ')
dady = dady:gsub('ل','لِٰـِۢ')
dady = dady:gsub('ا','آ')
dady = dady:gsub('ت','تِٰـِۢ')
dady = dady:gsub('ن','نِٰـِۢ')
dady = dady:gsub('م','مِٰـِۢ')
dady = dady:gsub('ك','ڪِٰـِۢ')
dady = dady:gsub('ط','طِٰـِۢ')
dady = dady:gsub('ظ','ظِٰـِۢ')
dady = dady:gsub('ء','ء')
dady = dady:gsub('ؤ','ؤ')
dady = dady:gsub('ر','ر')
dady = dady:gsub('ى','ى')
dady = dady:gsub('ز','ز')
dady = dady:gsub('و','ﯛ̲୭')
dady = dady:gsub('ه','ۿۿہ')
dady = dady:gsub('a','𝗮')
dady = dady:gsub('A','𝗔')
dady = dady:gsub("b","𝗯")
dady = dady:gsub("B","𝗕")
dady = dady:gsub("c","𝗰")
dady = dady:gsub("C","𝗖")
dady = dady:gsub("d","𝗱")
dady = dady:gsub("D","𝗗")
dady = dady:gsub("e","𝗲")
dady = dady:gsub("E","𝗘")
dady = dady:gsub("f","𝗳")
dady = dady:gsub("F","𝗙")
dady = dady:gsub("g","𝗴")
dady = dady:gsub("G","𝗚")
dady = dady:gsub("h","𝗵")
dady = dady:gsub("H","𝗛")
dady = dady:gsub("i","𝗹")
dady = dady:gsub("I","𝗜")
dady = dady:gsub("j","𝗝")
dady = dady:gsub("J","𝗝")
dady = dady:gsub("k","𝗸")
dady = dady:gsub("K","𝗞")
dady = dady:gsub("l","𝗹")
dady = dady:gsub("L","𝗟")
dady = dady:gsub("m","𝗺")
dady = dady:gsub("M","𝗠")
dady = dady:gsub("n","𝗻")
dady = dady:gsub("N","𝗡")
dady = dady:gsub("o","𝗼")
dady = dady:gsub("O","𝗢")
dady = dady:gsub("p","𝗽")
dady = dady:gsub("P","𝗣")
dady = dady:gsub("q","𝗾")
dady = dady:gsub("Q","𝗤")
dady = dady:gsub("r","𝗿")
dady = dady:gsub("R","𝗥")
dady = dady:gsub("s","𝘀")
dady = dady:gsub("S","𝗦")
dady = dady:gsub("t","𝘁")
dady = dady:gsub("T","𝗧")
dady = dady:gsub("u","𝘂")
dady = dady:gsub("U","𝗨")
dady = dady:gsub("v","𝘃")
dady = dady:gsub("V","𝗩")
dady = dady:gsub("w","𝘄")
dady = dady:gsub("W","𝗪")
dady = dady:gsub("x","𝘅")
dady = dady:gsub("X","𝗫")
dady = dady:gsub("y","𝘆")
dady = dady:gsub("Y","𝗬")
dady = dady:gsub("z","𝘇")
dady = dady:gsub("Z","𝗭")



local dady2 = Text:gsub('ض','ضَٰـُـٰٓ')
dady2 = dady2:gsub('ص','صَٰـُـٰٓ')
dady2 = dady2:gsub('ث','ثَٰـُـٰٓ')
dady2 = dady2:gsub('ق','قَٰـُـٰٓ')
dady2 = dady2:gsub('ف','فَٰ͒ـُـٰٓ')
dady2 = dady2:gsub('غ','غَٰـُـٰٓ')
dady2 = dady2:gsub('ع','عَٰـُـٰٓ')
dady2 = dady2:gsub('خ','خَٰ̐ـُـٰٓ')
dady2 = dady2:gsub('ح','حَٰـُـٰٓ')
dady2 = dady2:gsub('ج','جَٰـُـٰٓ')
dady2 = dady2:gsub('ش','شَٰـُـٰٓ')
dady2 = dady2:gsub('س','سَٰـُـٰٓ')
dady2 = dady2:gsub('ي','يَٰـُـٰٓ')
dady2 = dady2:gsub('ب','بَٰـُـٰٓ')
dady2 = dady2:gsub('ل','لَٰـُـٰٓ')
dady2 = dady2:gsub('ا','آ')
dady2 = dady2:gsub('ت','تَٰـُـٰٓ')
dady2 = dady2:gsub('ن','نَٰـُـٰٓ')
dady2 = dady2:gsub('م','مَٰـُـٰٓ')
dady2 = dady2:gsub('ك','ڪَٰـُـٰٓ')
dady2 = dady2:gsub('ط','طَٰـُـٰٓ')
dady2 = dady2:gsub('ظ','ظَٰـُـٰٓ')
dady2 = dady2:gsub('ء','ء')
dady2 = dady2:gsub('ؤ','ؤ')
dady2 = dady2:gsub('ر','ر')
dady2 = dady2:gsub('ى','ى')
dady2 = dady2:gsub('ز','ز')
dady2 = dady2:gsub('و','ﯛ̲୭')
dady2 = dady2:gsub("ه", "ۿۿہ")
dady2 = dady2:gsub('a',"𝖆")
dady2 = dady2:gsub('A',"𝖆")
dady2 = dady2:gsub("b","𝖇")
dady2 = dady2:gsub("B","𝖇")
dady2 = dady2:gsub("c","𝖈")
dady2 = dady2:gsub("C","𝖈")
dady2 = dady2:gsub("d","𝖉")
dady2 = dady2:gsub("D","𝖉")
dady2 = dady2:gsub("e","𝖊")
dady2 = dady2:gsub("E","𝖊")
dady2 = dady2:gsub("f","𝖋")
dady2 = dady2:gsub("F","𝖋")
dady2 = dady2:gsub("g","𝖌")
dady2 = dady2:gsub("G","𝖌")
dady2 = dady2:gsub("h","𝖍")
dady2 = dady2:gsub("H","𝖍")
dady2 = dady2:gsub("i","𝖎")
dady2 = dady2:gsub("I","𝖎")
dady2 = dady2:gsub("j","𝖏")
dady2 = dady2:gsub("J","𝖏")
dady2 = dady2:gsub("k","𝖐")
dady2 = dady2:gsub("K","𝖐")
dady2 = dady2:gsub("l","𝖑")
dady2 = dady2:gsub("L","𝖑")
dady2 = dady2:gsub("m","𝖒")
dady2 = dady2:gsub("M","𝖒")
dady2 = dady2:gsub("n","𝖓")
dady2 = dady2:gsub("N","𝖓")
dady2 = dady2:gsub("o","𝖔")
dady2 = dady2:gsub("O","𝖔")
dady2 = dady2:gsub("p","𝖕")
dady2 = dady2:gsub("P","𝖕")
dady2 = dady2:gsub("q","𝖖")
dady2 = dady2:gsub("Q","𝖖")
dady2 = dady2:gsub("r","𝖗")
dady2 = dady2:gsub("R","𝖗")
dady2 = dady2:gsub("s","𝖘")
dady2 = dady2:gsub("S","𝖘")
dady2 = dady2:gsub("t","𝖙")
dady2 = dady2:gsub("T","𝖙")
dady2 = dady2:gsub("u","𝖚")
dady2 = dady2:gsub("U","𝖚")
dady2 = dady2:gsub("v","𝖛")
dady2 = dady2:gsub("V","𝖛")
dady2 = dady2:gsub("w","𝖜")
dady2 = dady2:gsub("W","𝖜")
dady2 = dady2:gsub("x","𝖝")
dady2 = dady2:gsub("X","𝖝")
dady2 = dady2:gsub("y","𝖞")
dady2 = dady2:gsub("Y","𝖞")
dady2 = dady2:gsub("z","𝖟")
dady2 = dady2:gsub("Z","𝖟")


local dady3= Text:gsub('ض','ض')
dady3= dady3:gsub('ص','ص')
dady3= dady3:gsub('ث','ثہ')
dady3= dady3:gsub('ق','ق')
dady3= dady3:gsub('ف','فُہ')
dady3= dady3:gsub('غ','غہ')
dady3= dady3:gsub('ع','عہ')
dady3= dady3:gsub('ه','هٰہٰٖ')
dady3= dady3:gsub('خ','خہ')
dady3= dady3:gsub('ح','حہ')
dady3= dady3:gsub('ج','جہ')
dady3= dady3:gsub('د','د')
dady3= dady3:gsub('ذ','ذ')
dady3= dady3:gsub('ش','شہ')
dady3= dady3:gsub('س','سہ')
dady3= dady3:gsub('ي','يہ')
dady3= dady3:gsub('ب','بّ')
dady3= dady3:gsub('ل','لہ')
dady3= dady3:gsub('ا','ا')
dady3= dady3:gsub('ت','تہ')
dady3= dady3:gsub('ن','نٰہٰٖ')
dady3= dady3:gsub('م','مٰہٰٖ')
dady3= dady3:gsub('ك','كُہ')
dady3= dady3:gsub('ط','طہ')
dady3= dady3:gsub('ئ','ئ ْٰ')
dady3= dady3:gsub('ء','ء')
dady3= dady3:gsub('ؤ','ؤ')
dady3= dady3:gsub('ر','رَ')
dady3= dady3:gsub('لا','لہا')
dady3= dady3:gsub('ى','ىْ')
dady3= dady3:gsub('ة','ة')
dady3= dady3:gsub('و','و')
dady3= dady3:gsub('ز','ز')
dady3= dady3:gsub('ظ','ظۗہٰٰ')
dady3= dady3:gsub('q','𝐪')
dady3= dady3:gsub('Q','𝐪')
dady3= dady3:gsub('w','𝐰')
dady3= dady3:gsub('W','𝐰')
dady3= dady3:gsub('e','𝐞')
dady3= dady3:gsub('E','𝐞')
dady3= dady3:gsub('r','𝐫')
dady3= dady3:gsub('R','𝐫')
dady3= dady3:gsub('t','𝐭')
dady3= dady3:gsub('T','𝐭')
dady3= dady3:gsub('y','𝐲')
dady3= dady3:gsub('Y','𝐲')
dady3= dady3:gsub('u','𝐮')
dady3= dady3:gsub('i','𝐢')
dady3= dady3:gsub('o','𝐨')
dady3= dady3:gsub('p','𝐩')
dady3= dady3:gsub('a','𝐚')
dady3= dady3:gsub('s','𝐬')
dady3= dady3:gsub('d','𝐝')
dady3= dady3:gsub('f','𝐟')
dady3= dady3:gsub('g','𝐠')
dady3= dady3:gsub('h','𝐡')
dady3= dady3:gsub('j','𝐣')
dady3= dady3:gsub('k','𝐤')
dady3= dady3:gsub('U','𝐮')
dady3= dady3:gsub('I','𝐢')
dady3= dady3:gsub('O','𝐨')
dady3= dady3:gsub('P','𝐩')
dady3= dady3:gsub('A','𝐚')
dady3= dady3:gsub('S','𝐬')
dady3= dady3:gsub('D','𝐝')
dady3= dady3:gsub('F','𝐟')
dady3= dady3:gsub('G','𝐠')
dady3= dady3:gsub('H','𝐡')
dady3= dady3:gsub('J','𝐣')
dady3= dady3:gsub('K','𝐤')
dady3= dady3:gsub('L','𝐥')
dady3= dady3:gsub('l','𝐥')
dady3= dady3:gsub('z','𝐳')
dady3= dady3:gsub('Z','𝐳')
dady3= dady3:gsub('x','𝐱')
dady3= dady3:gsub('X','ẋ')
dady3= dady3:gsub('c','𝐜')
dady3= dady3:gsub('C','𝐜')
dady3= dady3:gsub('v','𝐯')
dady3= dady3:gsub('V','𝐯')
dady3= dady3:gsub('b','𝐛')
dady3= dady3:gsub('B','𝐛')
dady3= dady3:gsub('n','𝐧')
dady3= dady3:gsub('N','𝐧')
dady3= dady3:gsub('m','𝐦')
dady3= dady3:gsub('M','𝐦')


local dady4= Text:gsub('ض','ضۜہٰٰ')
dady4= dady4:gsub('ص','ضۜہٰٰ')
dady4= dady4:gsub('ث','ثہٰٰ')
dady4= dady4:gsub('ق','قྀ̲ہٰٰ')
dady4= dady4:gsub('ف','ف͒ہٰٰ')
dady4= dady4:gsub('غ','غہٰٰ')
dady4= dady4:gsub('ع','عہٰٰ')
dady4= dady4:gsub('ه','هٰہٰٖ')
dady4= dady4:gsub('خ','خٰ̐ہ ')
dady4= dady4:gsub('ح','حہٰٰ')
dady4= dady4:gsub('ج','جـٰ̲ـہْۧ')
dady4= dady4:gsub('د','دٰ')
dady4= dady4:gsub('ذ','ذِٰ')
dady4= dady4:gsub('ش','شِٰہٰٰ')
dady4= dady4:gsub('س','سٰٓ')
dady4= dady4:gsub('ي','يِٰہ')
dady4= dady4:gsub('ب','بّہ')
dady4= dady4:gsub('ل','لـٰ̲ـہ')
dady4= dady4:gsub('ا','آ')
dady4= dady4:gsub('ت','تَہَٰ')
dady4= dady4:gsub('ن','نَِہ')
dady4= dady4:gsub('م','مٰ̲ہ')
dady4= dady4:gsub('ك','ڪٰྀہٰٰ')
dady4= dady4:gsub('ط','طۨہٰٰ')
dady4= dady4:gsub('ئ','ئ ْٰ')
dady4= dady4:gsub('ء','ء')
dady4= dady4:gsub('ؤ','ؤ')
dady4= dady4:gsub('ر','رَ')
dady4= dady4:gsub('لا','لہا')
dady4= dady4:gsub('ى','ىْ')
dady4= dady4:gsub('ة','ة')
dady4= dady4:gsub('و','وِٰ')
dady4= dady4:gsub('ز','زَٰ')
dady4= dady4:gsub('ظ','ظۗہٰٰ')
dady4= dady4:gsub('q','𝑸')
dady4= dady4:gsub('Q','𝑸')
dady4= dady4:gsub('w','𝑾')
dady4= dady4:gsub('W','𝑾')
dady4= dady4:gsub('e','𝑬')
dady4= dady4:gsub('E','𝑬')
dady4= dady4:gsub('r','𝑹')
dady4= dady4:gsub('R','𝑹')
dady4= dady4:gsub('t','𝑻')
dady4= dady4:gsub('T','𝑻')
dady4= dady4:gsub('y','𝒀')
dady4= dady4:gsub('Y','𝒀')
dady4= dady4:gsub('u','𝑼')
dady4= dady4:gsub('U','𝑼')
dady4= dady4:gsub('i','𝑰')
dady4= dady4:gsub('I','𝑰')
dady4= dady4:gsub('o','𝑶')
dady4= dady4:gsub('O','𝑶')
dady4= dady4:gsub('p','𝑷')
dady4= dady4:gsub('P','𝑷')
dady4= dady4:gsub('a','𝑨')
dady4= dady4:gsub('A','𝑨')
dady4= dady4:gsub('s','𝑺')
dady4= dady4:gsub('S','𝑺')
dady4= dady4:gsub('d','𝑫')
dady4= dady4:gsub('D','𝑫')
dady4= dady4:gsub('f','𝑭')
dady4= dady4:gsub('F','𝑭')
dady4= dady4:gsub('g','𝑮')
dady4= dady4:gsub('G','𝑮')
dady4= dady4:gsub('h','𝑯')
dady4= dady4:gsub('H','𝑯')
dady4= dady4:gsub('j','𝑱')
dady4= dady4:gsub('J','𝑱')
dady4= dady4:gsub('k','𝑲')
dady4= dady4:gsub('K','𝑲')
dady4= dady4:gsub('l','𝑳')
dady4= dady4:gsub('L','𝑳')
dady4= dady4:gsub('z','𝒁')
dady4= dady4:gsub('Z','𝒁')
dady4= dady4:gsub('x','𝑿')
dady4= dady4:gsub('X','𝑿')
dady4= dady4:gsub('c','𝑪')
dady4= dady4:gsub('C','𝑪')
dady4= dady4:gsub('v','𝑽')
dady4= dady4:gsub('V','𝑽')
dady4= dady4:gsub('b','𝑩')
dady4= dady4:gsub('B','𝑩')
dady4= dady4:gsub('n','𝑵')
dady4= dady4:gsub('N','𝑵')
dady4= dady4:gsub('m','𝑴')
dady4= dady4:gsub('M','𝑴')



local dady5= Text:gsub('ض','ضَ')
dady5= dady5:gsub('ص','صً')
dady5= dady5:gsub('ث','ثَ')
dady5= dady5:gsub('ق','قُ')
dady5= dady5:gsub('ف','فّ')
dady5= dady5:gsub('غ','غِ')
dady5= dady5:gsub('ع','عُ')
dady5= dady5:gsub('ه','ﮭ')
dady5= dady5:gsub('خ','خِ')
dady5= dady5:gsub('ح','حٌ')
dady5= dady5:gsub('ج','جُ')
dady5= dady5:gsub('د','دِ')
dady5= dady5:gsub('ذ','ذَ')
dady5= dady5:gsub('ش','شِ')
dady5= dady5:gsub('س','سً')
dady5= dady5:gsub('ي','يْ')
dady5= dady5:gsub('ب','بّ')
dady5= dady5:gsub('ل','لَ')
dady5= dady5:gsub('ا','أُ')
dady5= dady5:gsub('ت','تٌ')
dady5= dady5:gsub('ن','نً')
dady5= dady5:gsub('م','مِ')
dady5= dady5:gsub('ك','ڳّ')
dady5= dady5:gsub('ط','طٌ')
dady5= dady5:gsub('ئ','ئ')
dady5= dady5:gsub('ء','ء')
dady5= dady5:gsub('ؤ','ؤ')
dady5= dady5:gsub('ر','رٌ')
dady5= dady5:gsub('لا','لٌأً')
dady5= dady5:gsub('ى','ى')
dady5= dady5:gsub('ة','ةَ')
dady5= dady5:gsub('و','وِ')
dady5= dady5:gsub('ز','زُ')
dady5= dady5:gsub('ظ','ظ')
dady5= dady5:gsub('q','𝒒')
dady5= dady5:gsub('Q','𝒒')
dady5= dady5:gsub('w','𝒘')
dady5= dady5:gsub('W','𝒘')
dady5= dady5:gsub('e','𝒆')
dady5= dady5:gsub('E','𝒆')
dady5= dady5:gsub('r','𝒓')
dady5= dady5:gsub('R','𝒓')
dady5= dady5:gsub('t','𝒕')
dady5= dady5:gsub('T','𝒕')
dady5= dady5:gsub('y','𝒚')
dady5= dady5:gsub('Y','𝒚')
dady5= dady5:gsub('u','𝒖')
dady5= dady5:gsub('U','𝒖')
dady5= dady5:gsub('i','𝒊')
dady5= dady5:gsub('I','𝒊')
dady5= dady5:gsub('o','𝒐')
dady5= dady5:gsub('O','𝒐')
dady5= dady5:gsub('p','𝒑')
dady5= dady5:gsub('P','𝒑')
dady5= dady5:gsub('a','𝒂')
dady5= dady5:gsub('A','𝒂')
dady5= dady5:gsub('s','𝒔')
dady5= dady5:gsub('S','𝒔')
dady5= dady5:gsub('d','𝒅')
dady5= dady5:gsub('D','𝒅')
dady5= dady5:gsub('f','𝒇')
dady5= dady5:gsub('F','𝒇')
dady5= dady5:gsub('g','𝒈')
dady5= dady5:gsub('G','𝒈')
dady5= dady5:gsub('h','𝒉')
dady5= dady5:gsub('H','𝒉')
dady5= dady5:gsub('j','𝒋')
dady5= dady5:gsub('J','𝒋')
dady5= dady5:gsub('K','𝒌')
dady5= dady5:gsub('k','𝒌')
dady5= dady5:gsub('L','𝒍')
dady5= dady5:gsub('l','𝒍')
dady5= dady5:gsub('z','𝒛')
dady5= dady5:gsub('Z','𝒛')
dady5= dady5:gsub('x','𝒙')
dady5= dady5:gsub('X','𝒙')
dady5= dady5:gsub('c','𝒄')
dady5= dady5:gsub('C','𝒄')
dady5= dady5:gsub('v','𝒗')
dady5= dady5:gsub('V','𝒗')
dady5= dady5:gsub('b','𝒃')
dady5= dady5:gsub('B','𝒃')
dady5= dady5:gsub('n','𝒏')
dady5= dady5:gsub('N','𝒏')
dady5= dady5:gsub('m','𝒎')
dady5= dady5:gsub('M','𝒎')



local dady6= Text:gsub('ض','ﺿ̭͠')
dady6= dady6:gsub('ص','ﺻ͡')
dady6= dady6:gsub('ث','ﺜ̲')
dady6= dady6:gsub('ق','ﭰ')
dady6= dady6:gsub('ف','ﻓ̲')
dady6= dady6:gsub('غ','ﻏ̲')
dady6= dady6:gsub('ع','ﻌ̲')
dady6= dady6:gsub('ه','ﮬ̲̌')
dady6= dady6:gsub('خ','خٌ')
dady6= dady6:gsub('ح','ﺣ̅')
dady6= dady6:gsub('ج','جُ')
dady6= dady6:gsub('د','ډ̝')
dady6= dady6:gsub('ذ','ذً')
dady6= dady6:gsub('ش','ﺷ̲')
dady6= dady6:gsub('س','ﺳ̉')
dady6= dady6:gsub('ي','ﯾ̃̐')
dady6= dady6:gsub('ب','ﺑ̲')
dady6= dady6:gsub('ل','ا̄ﻟ')
dady6= dady6:gsub('ا','ﺈ̃')
dady6= dady6:gsub('ت','ټُ')
dady6= dady6:gsub('ن','ﻧ̲')
dady6= dady6:gsub('م','ﻣ̲̉')
dady6= dady6:gsub('ك','گ')
dady6= dady6:gsub('ط','ﻁ̲')
dady6= dady6:gsub('ئ',' ْٰئ')
dady6= dady6:gsub('ء','ء')
dady6= dady6:gsub('ؤ','ؤ')
dady6= dady6:gsub('ر','ہڕ')
dady6= dady6:gsub('لا','ﻟ̲ﺂ̲')
dady6= dady6:gsub('ى','ى')
dady6= dady6:gsub('ة','ة')
dady6= dady6:gsub('و','ۇۈۉ')
dady6= dady6:gsub('ز','زُ')
dady6= dady6:gsub('ظ','ﻇ̲')
dady6= dady6:gsub('q','ǫ')
dady6= dady6:gsub('Q','ǫ')
dady6= dady6:gsub('w','ᴡ')
dady6= dady6:gsub('W','ᴡ')
dady6= dady6:gsub('e','ᴇ')
dady6= dady6:gsub('E','ᴇ')
dady6= dady6:gsub('r','ʀ')
dady6= dady6:gsub('R','ʀ')
dady6= dady6:gsub('t','ᴛ')
dady6= dady6:gsub('T','ᴛ')
dady6= dady6:gsub('y','ʏ')
dady6= dady6:gsub('Y','ʏ')
dady6= dady6:gsub('u','ụ')
dady6= dady6:gsub('U','ụ')
dady6= dady6:gsub('i','ɪ')
dady6= dady6:gsub('I','ɪ')
dady6= dady6:gsub('o','ᴏ')
dady6= dady6:gsub('O','ᴏ')
dady6= dady6:gsub('p','ᴘ')
dady6= dady6:gsub('P','ᴘ')
dady6= dady6:gsub('a','ᴀ')
dady6= dady6:gsub('A','ᴀ')
dady6= dady6:gsub('s','ѕ')
dady6= dady6:gsub('S','ѕ')
dady6= dady6:gsub('d','ᴅ')
dady6= dady6:gsub('D','ᴅ')
dady6= dady6:gsub('f','ғ')
dady6= dady6:gsub('F','ғ')
dady6= dady6:gsub('g','ɢ')
dady6= dady6:gsub('G','ɢ')
dady6= dady6:gsub('h','ʜ')
dady6= dady6:gsub('H','ʜ')
dady6= dady6:gsub('j','ᴊ')
dady6= dady6:gsub('J','ᴊ')
dady6= dady6:gsub('K','ᴋ')
dady6= dady6:gsub('k','ᴋ')
dady6= dady6:gsub('L','ʟ')
dady6= dady6:gsub('l','ʟ')
dady6= dady6:gsub('z','ᴢ')
dady6= dady6:gsub('Z','ᴢ')
dady6= dady6:gsub('x','х')
dady6= dady6:gsub('X','х')
dady6= dady6:gsub('c','ᴄ')
dady6= dady6:gsub('C','ᴄ')
dady6= dady6:gsub('v','ᴠ')
dady6= dady6:gsub('V','ᴠ')
dady6= dady6:gsub('b','ʙ')
dady6= dady6:gsub('B','ʙ')
dady6= dady6:gsub('n','ɴ')
dady6= dady6:gsub('N','ɴ')
dady6= dady6:gsub('m','ᴍ')
dady6= dady6:gsub('M','ᴍ')



local dady7= Text:gsub('ض','ﺿ')
dady7= dady7:gsub('ص','ﺻ')
dady7= dady7:gsub('ث','ﭥ')
dady7= dady7:gsub('ق','ﻗ̮ـ̃')
dady7= dady7:gsub('ف','ﭬ')
dady7= dady7:gsub('غ','ﻏ̣̐')
dady7= dady7:gsub('ع','ﻋ')
dady7= dady7:gsub('ه','ھَہّ')
dady7= dady7:gsub('خ','ﺧ')
dady7= dady7:gsub('ح','פ')
dady7= dady7:gsub('ج','ﭴ')
dady7= dady7:gsub('د','ﮃ')
dady7= dady7:gsub('ذ','ذ')
dady7= dady7:gsub('ش','ﺷ')
dady7= dady7:gsub('س','ﺳ')
dady7= dady7:gsub('ي','ﯾ')
dady7= dady7:gsub('ب','ﺑ')
dady7= dady7:gsub('ل','ﻟ')
dady7= dady7:gsub('ا','ﺂ')
dady7= dady7:gsub('ت','ﭠ')
dady7= dady7:gsub('ن','ﻧ')
dady7= dady7:gsub('م','ﻣ̝̚')
dady7= dady7:gsub('ك','گـ')
dady7= dady7:gsub('ط','ﻁْ')
dady7= dady7:gsub('ئ','ٰئـ')
dady7= dady7:gsub('ء','ء')
dady7= dady7:gsub('ؤ','ﯗ')
dady7= dady7:gsub('ر','ړُ')
dady7= dady7:gsub('لا','ﻟآ')
dady7= dady7:gsub('ى','ـﮯ')
dady7= dady7:gsub('ة','ة')
dady7= dady7:gsub('و','ۆ')
dady7= dady7:gsub('ز','ژ')
dady7= dady7:gsub('ظ','ﻅ')
dady7= dady7:gsub('q','𝘘')
dady7= dady7:gsub('Q','𝘘')
dady7= dady7:gsub('w','𝘞')
dady7= dady7:gsub('W','𝘞')
dady7= dady7:gsub('e','𝘌')
dady7= dady7:gsub('E','𝘌')
dady7= dady7:gsub('r','𝘙')
dady7= dady7:gsub('R','𝘙')
dady7= dady7:gsub('t','𝘛')
dady7= dady7:gsub('T','𝘛')
dady7= dady7:gsub('y','𝘠')
dady7= dady7:gsub('Y','𝘠')
dady7= dady7:gsub('u','𝘜')
dady7= dady7:gsub('U','𝘜')
dady7= dady7:gsub('i','𝘐')
dady7= dady7:gsub('I','𝘐')
dady7= dady7:gsub('o','𝘖')
dady7= dady7:gsub('O','𝘖')
dady7= dady7:gsub('p','𝘗')
dady7= dady7:gsub('P','𝘗')
dady7= dady7:gsub('a','𝘈')
dady7= dady7:gsub('A','𝘈')
dady7= dady7:gsub('s','𝘚')
dady7= dady7:gsub('S','𝘚')
dady7= dady7:gsub('d','𝘋')
dady7= dady7:gsub('D','𝘋')
dady7= dady7:gsub('f','𝘍')
dady7= dady7:gsub('F','𝘍')
dady7= dady7:gsub('g','𝘎')
dady7= dady7:gsub('G','𝘎')
dady7= dady7:gsub('h','𝘏')
dady7= dady7:gsub('H','𝘏')
dady7= dady7:gsub('j','𝘑')
dady7= dady7:gsub('J','𝘑')
dady7= dady7:gsub('k','𝘒')
dady7= dady7:gsub('K','𝘒')
dady7= dady7:gsub('L','𝘓')
dady7= dady7:gsub('l','𝘓')
dady7= dady7:gsub('z','𝘡')
dady7= dady7:gsub('Z','𝘡')
dady7= dady7:gsub('x','𝘟')
dady7= dady7:gsub('X','𝘟')
dady7= dady7:gsub('c','𝘊')
dady7= dady7:gsub('C','𝘊')
dady7= dady7:gsub('v','𝘝')
dady7= dady7:gsub('V','𝘝')
dady7= dady7:gsub('b','𝘉')
dady7= dady7:gsub('B','𝘉')
dady7= dady7:gsub('n','𝘕')
dady7= dady7:gsub('N','𝘕')
dady7= dady7:gsub('m','𝘔')
dady7= dady7:gsub('M','𝘔')



local dady8= Text:gsub('ض','ض');
dady8= dady8:gsub('ص','صہٰ')
dady8= dady8:gsub('ث','ثہٰـ')
dady8= dady8:gsub('ق','قہٰ')
dady8= dady8:gsub('ف','فہٰ')
dady8= dady8:gsub('غ','غـْ')
dady8= dady8:gsub('ع','ع')
dady8= dady8:gsub('ه','هٰہٰٖ')
dady8= dady8:gsub('خ','خخَـ')
dady8= dady8:gsub('ح','حہٰ')
dady8= dady8:gsub('ج','ججہٰ')
dady8= dady8:gsub('د','دَ')
dady8= dady8:gsub('ذ','ذّ')
dady8= dady8:gsub('ش','ششہٰ')
dady8= dady8:gsub('س','سہٰ')
dady8= dady8:gsub('ي','يٰ')
dady8= dady8:gsub('ب','بٰٰ')
dady8= dady8:gsub('ل','لہٰ')
dady8= dady8:gsub('ا','آ')
dady8= dady8:gsub('ت','تہٰ')
dady8= dady8:gsub('ن','نہٰ')
dady8= dady8:gsub('م','مہٰ')
dady8= dady8:gsub('ك','ككہٰ')
dady8= dady8:gsub('ط','طہٰ')
dady8= dady8:gsub('ئ',' ْئٰ')
dady8= dady8:gsub('ء','ء')
dady8= dady8:gsub('ؤ','ؤؤَ')
dady8= dady8:gsub('ر','رَ')
dady8= dady8:gsub('لا','لہٰا')
dady8= dady8:gsub('ى','ىہٰ')
dady8= dady8:gsub('ة','ة')
dady8= dady8:gsub('و','ہٰو')
dady8= dady8:gsub('ز','ز')
dady8= dady8:gsub('ظ','ظہٰ')
dady8= dady8:gsub('q','𝚀')
dady8= dady8:gsub('Q','𝚀')
dady8= dady8:gsub('w','𝚆')
dady8= dady8:gsub('W','𝚆')
dady8= dady8:gsub('e','𝙴')
dady8= dady8:gsub('E','𝙴')
dady8= dady8:gsub('r','𝚁')
dady8= dady8:gsub('R','𝚁')
dady8= dady8:gsub('t','𝚃')
dady8= dady8:gsub('T','𝚃')
dady8= dady8:gsub('y','𝚈')
dady8= dady8:gsub('Y','𝚈')
dady8= dady8:gsub('u','𝚄')
dady8= dady8:gsub('U','𝚄')
dady8= dady8:gsub('i','𝙸')
dady8= dady8:gsub('I','𝙸')
dady8= dady8:gsub('o','𝙾')
dady8= dady8:gsub('O','𝙾')
dady8= dady8:gsub('p','𝙿')
dady8= dady8:gsub('P','𝙿')
dady8= dady8:gsub('a','𝙰')
dady8= dady8:gsub('A','𝙰')
dady8= dady8:gsub('s','𝚂')
dady8= dady8:gsub('S','𝚂')
dady8= dady8:gsub('d','𝙳')
dady8= dady8:gsub('D','𝙳')
dady8= dady8:gsub('f','𝙵')
dady8= dady8:gsub('F','𝙵')
dady8= dady8:gsub('g','𝙶')
dady8= dady8:gsub('G','𝙶')
dady8= dady8:gsub('h','𝙷')
dady8= dady8:gsub('H','𝙷')
dady8= dady8:gsub('j','𝙹')
dady8= dady8:gsub('J','𝙹')
dady8= dady8:gsub('k','𝙺')
dady8= dady8:gsub('K','𝙺')
dady8= dady8:gsub('L','𝙻')
dady8= dady8:gsub('l','𝙻')
dady8= dady8:gsub('z','𝚉')
dady8= dady8:gsub('Z','𝚉')
dady8= dady8:gsub('x','𝚇')
dady8= dady8:gsub('X','𝚇')
dady8= dady8:gsub('c','𝙲')
dady8= dady8:gsub('C','𝙲')
dady8= dady8:gsub('v','𝚅')
dady8= dady8:gsub('V','𝚅')
dady8= dady8:gsub('b','𝙱')
dady8= dady8:gsub('B','𝙱')
dady8= dady8:gsub('n','𝙽')
dady8= dady8:gsub('N','𝙽')
dady8= dady8:gsub('m','𝙼')
dady8= dady8:gsub('M','𝙼')



local dady9= Text:gsub('ض','ض')
dady9= dady9:gsub('ص','ص')
dady9= dady9:gsub('ث','ث')
dady9= dady9:gsub('ق','قٌ')
dady9= dady9:gsub('ف','فُ')
dady9= dady9:gsub('غ','غ')
dady9= dady9:gsub('ع','عٍ')
dady9= dady9:gsub('ه','هـ')
dady9= dady9:gsub('خ','خـ')
dady9= dady9:gsub('ح','حٍ')
dady9= dady9:gsub('ج','جٍ')
dady9= dady9:gsub('د','دِ')
dady9= dady9:gsub('ذ','ذَ')
dady9= dady9:gsub('ش','شُ')
dady9= dady9:gsub('س','س')
dady9= dady9:gsub('ي','ي')
dady9= dady9:gsub('ب','بَ')
dady9= dady9:gsub('ل','لُِ')
dady9= dady9:gsub('ا','آ')
dady9= dady9:gsub('ت','ت')
dady9= dady9:gsub('ن','ن')
dady9= dady9:gsub('م','م')
dady9= dady9:gsub('ك','ڪ')
dady9= dady9:gsub('ط','طُ')
dady9= dady9:gsub('ئ','ئ ْٰ')
dady9= dady9:gsub('ء','ء')
dady9= dady9:gsub('ؤ','ؤ')
dady9= dady9:gsub('ر','ر')
dady9= dady9:gsub('لا','لُِآ')
dady9= dady9:gsub('ى','ىْ')
dady9= dady9:gsub('ة','ة')
dady9= dady9:gsub('و','وو')
dady9= dady9:gsub('ز','ز')
dady9= dady9:gsub('ظ','ظهُ')
dady9= dady9:gsub('q','ℚ')
dady9= dady9:gsub('Q','ℚ')
dady9= dady9:gsub('w','𝕎')
dady9= dady9:gsub('W','𝕎')
dady9= dady9:gsub('e','𝔼')
dady9= dady9:gsub('E','𝔼')
dady9= dady9:gsub('r','ℝ')
dady9= dady9:gsub('R','ℝ')
dady9= dady9:gsub('t','𝕋')
dady9= dady9:gsub('T','𝕋')
dady9= dady9:gsub('y','𝕐')
dady9= dady9:gsub('Y','𝕐')
dady9= dady9:gsub('u','𝕌')
dady9= dady9:gsub('U','𝕌')
dady9= dady9:gsub('i','𝕀')
dady9= dady9:gsub('I','𝕀')
dady9= dady9:gsub('o','𝕆')
dady9= dady9:gsub('O','𝕆')
dady9= dady9:gsub('p','ℙ')
dady9= dady9:gsub('P','ℙ')
dady9= dady9:gsub('a','𝔸')
dady9= dady9:gsub('A','𝔸')
dady9= dady9:gsub('s','𝕊')
dady9= dady9:gsub('S','𝕊')
dady9= dady9:gsub('d','𝔻')
dady9= dady9:gsub('D','𝔻')
dady9= dady9:gsub('f','𝔽')
dady9= dady9:gsub('F','𝔽')
dady9= dady9:gsub('g','𝔾')
dady9= dady9:gsub('G','𝔾')
dady9= dady9:gsub('h','ℍ')
dady9= dady9:gsub('H','ℍ')
dady9= dady9:gsub('j','𝕁')
dady9= dady9:gsub('J','𝕁')
dady9= dady9:gsub('k','𝕂')
dady9= dady9:gsub('K','𝕂')
dady9= dady9:gsub('L','𝕃')
dady9= dady9:gsub('l','𝕃')
dady9= dady9:gsub('z','ℤ')
dady9= dady9:gsub('Z','ℤ')
dady9= dady9:gsub('x','𝕏')
dady9= dady9:gsub('X','𝕏')
dady9= dady9:gsub('c','ℂ')
dady9= dady9:gsub('C','ℂ')
dady9= dady9:gsub('v','𝕍')
dady9= dady9:gsub('V','𝕍')
dady9= dady9:gsub('b','𝔹')
dady9= dady9:gsub('B','𝔹')
dady9= dady9:gsub('n','ℕ')
dady9= dady9:gsub('N','ℕ')
dady9= dady9:gsub('m','𝕄')
dady9= dady9:gsub('M','𝕄')


local Text_dadya = "1- `"..dady..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..dady2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..dady3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..dady4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..dady5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..dady6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..dady7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..dady8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..dady9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..dady5..Emoje[math.random(#Emoje)]
Text_dadya = Text_dadya.."`\n\n اضغط علـي الاسـم ليـتم النـسخ \n★"
sendMsg(msg.chat_id_,msg.id_,Text_dadya)
return false
end
end

end
local function TextRes(msg)

if msg.text and msg.type ~= "pv" and redis:get(dady..":dadyNow:"..msg.sender_user_id_) then
Text = msg.text
redis:del(dady..":dadyNow:"..msg.sender_user_id_)
if utf8.len(msg.text) > 300 then
sendMsg(msg.chat_id_,msg.id_," لا يمكنك زخرفه اكثر من 300 حرف \n  ارسل امر زخرفه وحاول مجددا بحروف اقل")    
return false
end
local EmojeS = {
' 𓁻',
' 𓏴  ',
' 𓏶 ',
' 𓏡',
' 𓏢', 
' 𓏣', 
' ☽‘',
' 𖠱²²', 
'▽', 
' 𖡛“', 
' 𖡚℡', 
' 𖡨', 
}

local Emoje = {
' ♕',
' 𖤍',
'˛𖤓',
' ཻ ☫',
' ♫ ',
' 𖠶 ',
' 𖠲',
' 𖡥',
'  ☬',
' 𖤐',
' 𓇼',
' ♘  '
}


local dady = Text:gsub('ض','ضِٰـِۢ')
dady = dady:gsub('ص','صِٰـِۢ')
dady = dady:gsub('ث','ثِٰـِۢ')
dady = dady:gsub('ق','قِٰـِۢ')
dady = dady:gsub('ف','فِٰ͒ـِۢ')
dady = dady:gsub('غ','غِٰـِۢ')
dady = dady:gsub('ع','عِٰـِۢ')
dady = dady:gsub('خ','خِٰ̐ـِۢ')
dady = dady:gsub('ح','حِٰـِۢ')
dady = dady:gsub('ج','جِٰـِۢ')
dady = dady:gsub('ش','شِٰـِۢ')
dady = dady:gsub('س','سِٰـِۢ')
dady = dady:gsub('ي','يِٰـِۢ')
dady = dady:gsub('ب','بِٰـِۢ')
dady = dady:gsub('ل','لِٰـِۢ')
dady = dady:gsub('ا','آ')
dady = dady:gsub('ت','تِٰـِۢ')
dady = dady:gsub('ن','نِٰـِۢ')
dady = dady:gsub('م','مِٰـِۢ')
dady = dady:gsub('ك','ڪِٰـِۢ')
dady = dady:gsub('ط','طِٰـِۢ')
dady = dady:gsub('ظ','ظِٰـِۢ')
dady = dady:gsub('ء','ء')
dady = dady:gsub('ؤ','ؤ')
dady = dady:gsub('ر','ر')
dady = dady:gsub('ى','ى')
dady = dady:gsub('ز','ز')
dady = dady:gsub('و','ﯛ̲୭')
dady = dady:gsub('ه','ۿۿہ')
dady = dady:gsub('a','𝗮')
dady = dady:gsub('A','𝗔')
dady = dady:gsub("b","𝗯")
dady = dady:gsub("B","𝗕")
dady = dady:gsub("c","𝗰")
dady = dady:gsub("C","𝗖")
dady = dady:gsub("d","𝗱")
dady = dady:gsub("D","𝗗")
dady = dady:gsub("e","𝗲")
dady = dady:gsub("E","𝗘")
dady = dady:gsub("f","𝗳")
dady = dady:gsub("F","𝗙")
dady = dady:gsub("g","𝗴")
dady = dady:gsub("G","𝗚")
dady = dady:gsub("h","𝗵")
dady = dady:gsub("H","𝗛")
dady = dady:gsub("i","𝗹")
dady = dady:gsub("I","𝗜")
dady = dady:gsub("j","𝗝")
dady = dady:gsub("J","𝗝")
dady = dady:gsub("k","𝗸")
dady = dady:gsub("K","𝗞")
dady = dady:gsub("l","𝗹")
dady = dady:gsub("L","𝗟")
dady = dady:gsub("m","𝗺")
dady = dady:gsub("M","𝗠")
dady = dady:gsub("n","𝗻")
dady = dady:gsub("N","𝗡")
dady = dady:gsub("o","𝗼")
dady = dady:gsub("O","𝗢")
dady = dady:gsub("p","𝗽")
dady = dady:gsub("P","𝗣")
dady = dady:gsub("q","𝗾")
dady = dady:gsub("Q","𝗤")
dady = dady:gsub("r","𝗿")
dady = dady:gsub("R","𝗥")
dady = dady:gsub("s","𝘀")
dady = dady:gsub("S","𝗦")
dady = dady:gsub("t","𝘁")
dady = dady:gsub("T","𝗧")
dady = dady:gsub("u","𝘂")
dady = dady:gsub("U","𝗨")
dady = dady:gsub("v","𝘃")
dady = dady:gsub("V","𝗩")
dady = dady:gsub("w","𝘄")
dady = dady:gsub("W","𝗪")
dady = dady:gsub("x","𝘅")
dady = dady:gsub("X","𝗫")
dady = dady:gsub("y","𝘆")
dady = dady:gsub("Y","𝗬")
dady = dady:gsub("z","𝘇")
dady = dady:gsub("Z","𝗭")



local dady2 = Text:gsub('ض','ضَٰـُـٰٓ')
dady2 = dady2:gsub('ص','صَٰـُـٰٓ')
dady2 = dady2:gsub('ث','ثَٰـُـٰٓ')
dady2 = dady2:gsub('ق','قَٰـُـٰٓ')
dady2 = dady2:gsub('ف','فَٰ͒ـُـٰٓ')
dady2 = dady2:gsub('غ','غَٰـُـٰٓ')
dady2 = dady2:gsub('ع','عَٰـُـٰٓ')
dady2 = dady2:gsub('خ','خَٰ̐ـُـٰٓ')
dady2 = dady2:gsub('ح','حَٰـُـٰٓ')
dady2 = dady2:gsub('ج','جَٰـُـٰٓ')
dady2 = dady2:gsub('ش','شَٰـُـٰٓ')
dady2 = dady2:gsub('س','سَٰـُـٰٓ')
dady2 = dady2:gsub('ي','يَٰـُـٰٓ')
dady2 = dady2:gsub('ب','بَٰـُـٰٓ')
dady2 = dady2:gsub('ل','لَٰـُـٰٓ')
dady2 = dady2:gsub('ا','آ')
dady2 = dady2:gsub('ت','تَٰـُـٰٓ')
dady2 = dady2:gsub('ن','نَٰـُـٰٓ')
dady2 = dady2:gsub('م','مَٰـُـٰٓ')
dady2 = dady2:gsub('ك','ڪَٰـُـٰٓ')
dady2 = dady2:gsub('ط','طَٰـُـٰٓ')
dady2 = dady2:gsub('ظ','ظَٰـُـٰٓ')
dady2 = dady2:gsub('ء','ء')
dady2 = dady2:gsub('ؤ','ؤ')
dady2 = dady2:gsub('ر','ر')
dady2 = dady2:gsub('ى','ى')
dady2 = dady2:gsub('ز','ز')
dady2 = dady2:gsub('و','ﯛ̲୭')
dady2 = dady2:gsub("ه", "ۿۿہ")
dady2 = dady2:gsub('a',"𝖆")
dady2 = dady2:gsub('A',"𝖆")
dady2 = dady2:gsub("b","𝖇")
dady2 = dady2:gsub("B","𝖇")
dady2 = dady2:gsub("c","𝖈")
dady2 = dady2:gsub("C","𝖈")
dady2 = dady2:gsub("d","𝖉")
dady2 = dady2:gsub("D","𝖉")
dady2 = dady2:gsub("e","𝖊")
dady2 = dady2:gsub("E","𝖊")
dady2 = dady2:gsub("f","𝖋")
dady2 = dady2:gsub("F","𝖋")
dady2 = dady2:gsub("g","𝖌")
dady2 = dady2:gsub("G","𝖌")
dady2 = dady2:gsub("h","𝖍")
dady2 = dady2:gsub("H","𝖍")
dady2 = dady2:gsub("i","𝖎")
dady2 = dady2:gsub("I","𝖎")
dady2 = dady2:gsub("j","𝖏")
dady2 = dady2:gsub("J","𝖏")
dady2 = dady2:gsub("k","𝖐")
dady2 = dady2:gsub("K","𝖐")
dady2 = dady2:gsub("l","𝖑")
dady2 = dady2:gsub("L","𝖑")
dady2 = dady2:gsub("m","𝖒")
dady2 = dady2:gsub("M","𝖒")
dady2 = dady2:gsub("n","𝖓")
dady2 = dady2:gsub("N","𝖓")
dady2 = dady2:gsub("o","𝖔")
dady2 = dady2:gsub("O","𝖔")
dady2 = dady2:gsub("p","𝖕")
dady2 = dady2:gsub("P","𝖕")
dady2 = dady2:gsub("q","𝖖")
dady2 = dady2:gsub("Q","𝖖")
dady2 = dady2:gsub("r","𝖗")
dady2 = dady2:gsub("R","𝖗")
dady2 = dady2:gsub("s","𝖘")
dady2 = dady2:gsub("S","𝖘")
dady2 = dady2:gsub("t","𝖙")
dady2 = dady2:gsub("T","𝖙")
dady2 = dady2:gsub("u","𝖚")
dady2 = dady2:gsub("U","𝖚")
dady2 = dady2:gsub("v","𝖛")
dady2 = dady2:gsub("V","𝖛")
dady2 = dady2:gsub("w","𝖜")
dady2 = dady2:gsub("W","𝖜")
dady2 = dady2:gsub("x","𝖝")
dady2 = dady2:gsub("X","𝖝")
dady2 = dady2:gsub("y","𝖞")
dady2 = dady2:gsub("Y","𝖞")
dady2 = dady2:gsub("z","𝖟")
dady2 = dady2:gsub("Z","𝖟")


local dady3= Text:gsub('ض','ض')
dady3= dady3:gsub('ص','ص')
dady3= dady3:gsub('ث','ثہ')
dady3= dady3:gsub('ق','ق')
dady3= dady3:gsub('ف','فُہ')
dady3= dady3:gsub('غ','غہ')
dady3= dady3:gsub('ع','عہ')
dady3= dady3:gsub('ه','هٰہٰٖ')
dady3= dady3:gsub('خ','خہ')
dady3= dady3:gsub('ح','حہ')
dady3= dady3:gsub('ج','جہ')
dady3= dady3:gsub('د','د')
dady3= dady3:gsub('ذ','ذ')
dady3= dady3:gsub('ش','شہ')
dady3= dady3:gsub('س','سہ')
dady3= dady3:gsub('ي','يہ')
dady3= dady3:gsub('ب','بّ')
dady3= dady3:gsub('ل','لہ')
dady3= dady3:gsub('ا','ا')
dady3= dady3:gsub('ت','تہ')
dady3= dady3:gsub('ن','نٰہٰٖ')
dady3= dady3:gsub('م','مٰہٰٖ')
dady3= dady3:gsub('ك','كُہ')
dady3= dady3:gsub('ط','طہ')
dady3= dady3:gsub('ئ','ئ ْٰ')
dady3= dady3:gsub('ء','ء')
dady3= dady3:gsub('ؤ','ؤ')
dady3= dady3:gsub('ر','رَ')
dady3= dady3:gsub('لا','لہا')
dady3= dady3:gsub('ى','ىْ')
dady3= dady3:gsub('ة','ة')
dady3= dady3:gsub('و','و')
dady3= dady3:gsub('ز','ز')
dady3= dady3:gsub('ظ','ظۗہٰٰ')
dady3= dady3:gsub('q','𝐪')
dady3= dady3:gsub('Q','𝐪')
dady3= dady3:gsub('w','𝐰')
dady3= dady3:gsub('W','𝐰')
dady3= dady3:gsub('e','𝐞')
dady3= dady3:gsub('E','𝐞')
dady3= dady3:gsub('r','𝐫')
dady3= dady3:gsub('R','𝐫')
dady3= dady3:gsub('t','𝐭')
dady3= dady3:gsub('T','𝐭')
dady3= dady3:gsub('y','𝐲')
dady3= dady3:gsub('Y','𝐲')
dady3= dady3:gsub('u','𝐮')
dady3= dady3:gsub('i','𝐢')
dady3= dady3:gsub('o','𝐨')
dady3= dady3:gsub('p','𝐩')
dady3= dady3:gsub('a','𝐚')
dady3= dady3:gsub('s','𝐬')
dady3= dady3:gsub('d','𝐝')
dady3= dady3:gsub('f','𝐟')
dady3= dady3:gsub('g','𝐠')
dady3= dady3:gsub('h','𝐡')
dady3= dady3:gsub('j','𝐣')
dady3= dady3:gsub('k','𝐤')
dady3= dady3:gsub('U','𝐮')
dady3= dady3:gsub('I','𝐢')
dady3= dady3:gsub('O','𝐨')
dady3= dady3:gsub('P','𝐩')
dady3= dady3:gsub('A','𝐚')
dady3= dady3:gsub('S','𝐬')
dady3= dady3:gsub('D','𝐝')
dady3= dady3:gsub('F','𝐟')
dady3= dady3:gsub('G','𝐠')
dady3= dady3:gsub('H','𝐡')
dady3= dady3:gsub('J','𝐣')
dady3= dady3:gsub('K','𝐤')
dady3= dady3:gsub('L','𝐥')
dady3= dady3:gsub('l','𝐥')
dady3= dady3:gsub('z','𝐳')
dady3= dady3:gsub('Z','𝐳')
dady3= dady3:gsub('x','𝐱')
dady3= dady3:gsub('X','ẋ')
dady3= dady3:gsub('c','𝐜')
dady3= dady3:gsub('C','𝐜')
dady3= dady3:gsub('v','𝐯')
dady3= dady3:gsub('V','𝐯')
dady3= dady3:gsub('b','𝐛')
dady3= dady3:gsub('B','𝐛')
dady3= dady3:gsub('n','𝐧')
dady3= dady3:gsub('N','𝐧')
dady3= dady3:gsub('m','𝐦')
dady3= dady3:gsub('M','𝐦')


local dady4= Text:gsub('ض','ضۜہٰٰ')
dady4= dady4:gsub('ص','ضۜہٰٰ')
dady4= dady4:gsub('ث','ثہٰٰ')
dady4= dady4:gsub('ق','قྀ̲ہٰٰ')
dady4= dady4:gsub('ف','ف͒ہٰٰ')
dady4= dady4:gsub('غ','غہٰٰ')
dady4= dady4:gsub('ع','عہٰٰ')
dady4= dady4:gsub('ه','هٰہٰٖ')
dady4= dady4:gsub('خ','خٰ̐ہ ')
dady4= dady4:gsub('ح','حہٰٰ')
dady4= dady4:gsub('ج','جـٰ̲ـہْۧ')
dady4= dady4:gsub('د','دٰ')
dady4= dady4:gsub('ذ','ذِٰ')
dady4= dady4:gsub('ش','شِٰہٰٰ')
dady4= dady4:gsub('س','سٰٓ')
dady4= dady4:gsub('ي','يِٰہ')
dady4= dady4:gsub('ب','بّہ')
dady4= dady4:gsub('ل','لـٰ̲ـہ')
dady4= dady4:gsub('ا','آ')
dady4= dady4:gsub('ت','تَہَٰ')
dady4= dady4:gsub('ن','نَِہ')
dady4= dady4:gsub('م','مٰ̲ہ')
dady4= dady4:gsub('ك','ڪٰྀہٰٰ')
dady4= dady4:gsub('ط','طۨہٰٰ')
dady4= dady4:gsub('ئ','ئ ْٰ')
dady4= dady4:gsub('ء','ء')
dady4= dady4:gsub('ؤ','ؤ')
dady4= dady4:gsub('ر','رَ')
dady4= dady4:gsub('لا','لہا')
dady4= dady4:gsub('ى','ىْ')
dady4= dady4:gsub('ة','ة')
dady4= dady4:gsub('و','وِٰ')
dady4= dady4:gsub('ز','زَٰ')
dady4= dady4:gsub('ظ','ظۗہٰٰ')
dady4= dady4:gsub('q','𝑸')
dady4= dady4:gsub('Q','𝑸')
dady4= dady4:gsub('w','𝑾')
dady4= dady4:gsub('W','𝑾')
dady4= dady4:gsub('e','𝑬')
dady4= dady4:gsub('E','𝑬')
dady4= dady4:gsub('r','𝑹')
dady4= dady4:gsub('R','𝑹')
dady4= dady4:gsub('t','𝑻')
dady4= dady4:gsub('T','𝑻')
dady4= dady4:gsub('y','𝒀')
dady4= dady4:gsub('Y','𝒀')
dady4= dady4:gsub('u','𝑼')
dady4= dady4:gsub('U','𝑼')
dady4= dady4:gsub('i','𝑰')
dady4= dady4:gsub('I','𝑰')
dady4= dady4:gsub('o','𝑶')
dady4= dady4:gsub('O','𝑶')
dady4= dady4:gsub('p','𝑷')
dady4= dady4:gsub('P','𝑷')
dady4= dady4:gsub('a','𝑨')
dady4= dady4:gsub('A','𝑨')
dady4= dady4:gsub('s','𝑺')
dady4= dady4:gsub('S','𝑺')
dady4= dady4:gsub('d','𝑫')
dady4= dady4:gsub('D','𝑫')
dady4= dady4:gsub('f','𝑭')
dady4= dady4:gsub('F','𝑭')
dady4= dady4:gsub('g','𝑮')
dady4= dady4:gsub('G','𝑮')
dady4= dady4:gsub('h','𝑯')
dady4= dady4:gsub('H','𝑯')
dady4= dady4:gsub('j','𝑱')
dady4= dady4:gsub('J','𝑱')
dady4= dady4:gsub('k','𝑲')
dady4= dady4:gsub('K','𝑲')
dady4= dady4:gsub('l','𝑳')
dady4= dady4:gsub('L','𝑳')
dady4= dady4:gsub('z','𝒁')
dady4= dady4:gsub('Z','𝒁')
dady4= dady4:gsub('x','𝑿')
dady4= dady4:gsub('X','𝑿')
dady4= dady4:gsub('c','𝑪')
dady4= dady4:gsub('C','𝑪')
dady4= dady4:gsub('v','𝑽')
dady4= dady4:gsub('V','𝑽')
dady4= dady4:gsub('b','𝑩')
dady4= dady4:gsub('B','𝑩')
dady4= dady4:gsub('n','𝑵')
dady4= dady4:gsub('N','𝑵')
dady4= dady4:gsub('m','𝑴')
dady4= dady4:gsub('M','𝑴')



local dady5= Text:gsub('ض','ضَ')
dady5= dady5:gsub('ص','صً')
dady5= dady5:gsub('ث','ثَ')
dady5= dady5:gsub('ق','قُ')
dady5= dady5:gsub('ف','فّ')
dady5= dady5:gsub('غ','غِ')
dady5= dady5:gsub('ع','عُ')
dady5= dady5:gsub('ه','ﮭ')
dady5= dady5:gsub('خ','خِ')
dady5= dady5:gsub('ح','حٌ')
dady5= dady5:gsub('ج','جُ')
dady5= dady5:gsub('د','دِ')
dady5= dady5:gsub('ذ','ذَ')
dady5= dady5:gsub('ش','شِ')
dady5= dady5:gsub('س','سً')
dady5= dady5:gsub('ي','يْ')
dady5= dady5:gsub('ب','بّ')
dady5= dady5:gsub('ل','لَ')
dady5= dady5:gsub('ا','أُ')
dady5= dady5:gsub('ت','تٌ')
dady5= dady5:gsub('ن','نً')
dady5= dady5:gsub('م','مِ')
dady5= dady5:gsub('ك','ڳّ')
dady5= dady5:gsub('ط','طٌ')
dady5= dady5:gsub('ئ','ئ')
dady5= dady5:gsub('ء','ء')
dady5= dady5:gsub('ؤ','ؤ')
dady5= dady5:gsub('ر','رٌ')
dady5= dady5:gsub('لا','لٌأً')
dady5= dady5:gsub('ى','ى')
dady5= dady5:gsub('ة','ةَ')
dady5= dady5:gsub('و','وِ')
dady5= dady5:gsub('ز','زُ')
dady5= dady5:gsub('ظ','ظ')
dady5= dady5:gsub('q','𝒒')
dady5= dady5:gsub('Q','𝒒')
dady5= dady5:gsub('w','𝒘')
dady5= dady5:gsub('W','𝒘')
dady5= dady5:gsub('e','𝒆')
dady5= dady5:gsub('E','𝒆')
dady5= dady5:gsub('r','𝒓')
dady5= dady5:gsub('R','𝒓')
dady5= dady5:gsub('t','𝒕')
dady5= dady5:gsub('T','𝒕')
dady5= dady5:gsub('y','𝒚')
dady5= dady5:gsub('Y','𝒚')
dady5= dady5:gsub('u','𝒖')
dady5= dady5:gsub('U','𝒖')
dady5= dady5:gsub('i','𝒊')
dady5= dady5:gsub('I','𝒊')
dady5= dady5:gsub('o','𝒐')
dady5= dady5:gsub('O','𝒐')
dady5= dady5:gsub('p','𝒑')
dady5= dady5:gsub('P','𝒑')
dady5= dady5:gsub('a','𝒂')
dady5= dady5:gsub('A','𝒂')
dady5= dady5:gsub('s','𝒔')
dady5= dady5:gsub('S','𝒔')
dady5= dady5:gsub('d','𝒅')
dady5= dady5:gsub('D','𝒅')
dady5= dady5:gsub('f','𝒇')
dady5= dady5:gsub('F','𝒇')
dady5= dady5:gsub('g','𝒈')
dady5= dady5:gsub('G','𝒈')
dady5= dady5:gsub('h','𝒉')
dady5= dady5:gsub('H','𝒉')
dady5= dady5:gsub('j','𝒋')
dady5= dady5:gsub('J','𝒋')
dady5= dady5:gsub('K','𝒌')
dady5= dady5:gsub('k','𝒌')
dady5= dady5:gsub('L','𝒍')
dady5= dady5:gsub('l','𝒍')
dady5= dady5:gsub('z','𝒛')
dady5= dady5:gsub('Z','𝒛')
dady5= dady5:gsub('x','𝒙')
dady5= dady5:gsub('X','𝒙')
dady5= dady5:gsub('c','𝒄')
dady5= dady5:gsub('C','𝒄')
dady5= dady5:gsub('v','𝒗')
dady5= dady5:gsub('V','𝒗')
dady5= dady5:gsub('b','𝒃')
dady5= dady5:gsub('B','𝒃')
dady5= dady5:gsub('n','𝒏')
dady5= dady5:gsub('N','𝒏')
dady5= dady5:gsub('m','𝒎')
dady5= dady5:gsub('M','𝒎')



local dady6= Text:gsub('ض','ﺿ̭͠')
dady6= dady6:gsub('ص','ﺻ͡')
dady6= dady6:gsub('ث','ﺜ̲')
dady6= dady6:gsub('ق','ﭰ')
dady6= dady6:gsub('ف','ﻓ̲')
dady6= dady6:gsub('غ','ﻏ̲')
dady6= dady6:gsub('ع','ﻌ̲')
dady6= dady6:gsub('ه','ﮬ̲̌')
dady6= dady6:gsub('خ','خٌ')
dady6= dady6:gsub('ح','ﺣ̅')
dady6= dady6:gsub('ج','جُ')
dady6= dady6:gsub('د','ډ̝')
dady6= dady6:gsub('ذ','ذً')
dady6= dady6:gsub('ش','ﺷ̲')
dady6= dady6:gsub('س','ﺳ̉')
dady6= dady6:gsub('ي','ﯾ̃̐')
dady6= dady6:gsub('ب','ﺑ̲')
dady6= dady6:gsub('ل','ا̄ﻟ')
dady6= dady6:gsub('ا','ﺈ̃')
dady6= dady6:gsub('ت','ټُ')
dady6= dady6:gsub('ن','ﻧ̲')
dady6= dady6:gsub('م','ﻣ̲̉')
dady6= dady6:gsub('ك','گ')
dady6= dady6:gsub('ط','ﻁ̲')
dady6= dady6:gsub('ئ',' ْٰئ')
dady6= dady6:gsub('ء','ء')
dady6= dady6:gsub('ؤ','ؤ')
dady6= dady6:gsub('ر','ہڕ')
dady6= dady6:gsub('لا','ﻟ̲ﺂ̲')
dady6= dady6:gsub('ى','ى')
dady6= dady6:gsub('ة','ة')
dady6= dady6:gsub('و','ۇۈۉ')
dady6= dady6:gsub('ز','زُ')
dady6= dady6:gsub('ظ','ﻇ̲')
dady6= dady6:gsub('q','ǫ')
dady6= dady6:gsub('Q','ǫ')
dady6= dady6:gsub('w','ᴡ')
dady6= dady6:gsub('W','ᴡ')
dady6= dady6:gsub('e','ᴇ')
dady6= dady6:gsub('E','ᴇ')
dady6= dady6:gsub('r','ʀ')
dady6= dady6:gsub('R','ʀ')
dady6= dady6:gsub('t','ᴛ')
dady6= dady6:gsub('T','ᴛ')
dady6= dady6:gsub('y','ʏ')
dady6= dady6:gsub('Y','ʏ')
dady6= dady6:gsub('u','ụ')
dady6= dady6:gsub('U','ụ')
dady6= dady6:gsub('i','ɪ')
dady6= dady6:gsub('I','ɪ')
dady6= dady6:gsub('o','ᴏ')
dady6= dady6:gsub('O','ᴏ')
dady6= dady6:gsub('p','ᴘ')
dady6= dady6:gsub('P','ᴘ')
dady6= dady6:gsub('a','ᴀ')
dady6= dady6:gsub('A','ᴀ')
dady6= dady6:gsub('s','ѕ')
dady6= dady6:gsub('S','ѕ')
dady6= dady6:gsub('d','ᴅ')
dady6= dady6:gsub('D','ᴅ')
dady6= dady6:gsub('f','ғ')
dady6= dady6:gsub('F','ғ')
dady6= dady6:gsub('g','ɢ')
dady6= dady6:gsub('G','ɢ')
dady6= dady6:gsub('h','ʜ')
dady6= dady6:gsub('H','ʜ')
dady6= dady6:gsub('j','ᴊ')
dady6= dady6:gsub('J','ᴊ')
dady6= dady6:gsub('K','ᴋ')
dady6= dady6:gsub('k','ᴋ')
dady6= dady6:gsub('L','ʟ')
dady6= dady6:gsub('l','ʟ')
dady6= dady6:gsub('z','ᴢ')
dady6= dady6:gsub('Z','ᴢ')
dady6= dady6:gsub('x','х')
dady6= dady6:gsub('X','х')
dady6= dady6:gsub('c','ᴄ')
dady6= dady6:gsub('C','ᴄ')
dady6= dady6:gsub('v','ᴠ')
dady6= dady6:gsub('V','ᴠ')
dady6= dady6:gsub('b','ʙ')
dady6= dady6:gsub('B','ʙ')
dady6= dady6:gsub('n','ɴ')
dady6= dady6:gsub('N','ɴ')
dady6= dady6:gsub('m','ᴍ')
dady6= dady6:gsub('M','ᴍ')



local dady7= Text:gsub('ض','ﺿ')
dady7= dady7:gsub('ص','ﺻ')
dady7= dady7:gsub('ث','ﭥ')
dady7= dady7:gsub('ق','ﻗ̮ـ̃')
dady7= dady7:gsub('ف','ﭬ')
dady7= dady7:gsub('غ','ﻏ̣̐')
dady7= dady7:gsub('ع','ﻋ')
dady7= dady7:gsub('ه','ھَہّ')
dady7= dady7:gsub('خ','ﺧ')
dady7= dady7:gsub('ح','פ')
dady7= dady7:gsub('ج','ﭴ')
dady7= dady7:gsub('د','ﮃ')
dady7= dady7:gsub('ذ','ذ')
dady7= dady7:gsub('ش','ﺷ')
dady7= dady7:gsub('س','ﺳ')
dady7= dady7:gsub('ي','ﯾ')
dady7= dady7:gsub('ب','ﺑ')
dady7= dady7:gsub('ل','ﻟ')
dady7= dady7:gsub('ا','ﺂ')
dady7= dady7:gsub('ت','ﭠ')
dady7= dady7:gsub('ن','ﻧ')
dady7= dady7:gsub('م','ﻣ̝̚')
dady7= dady7:gsub('ك','گـ')
dady7= dady7:gsub('ط','ﻁْ')
dady7= dady7:gsub('ئ','ٰئـ')
dady7= dady7:gsub('ء','ء')
dady7= dady7:gsub('ؤ','ﯗ')
dady7= dady7:gsub('ر','ړُ')
dady7= dady7:gsub('لا','ﻟآ')
dady7= dady7:gsub('ى','ـﮯ')
dady7= dady7:gsub('ة','ة')
dady7= dady7:gsub('و','ۆ')
dady7= dady7:gsub('ز','ژ')
dady7= dady7:gsub('ظ','ﻅ')
dady7= dady7:gsub('q','𝘘')
dady7= dady7:gsub('Q','𝘘')
dady7= dady7:gsub('w','𝘞')
dady7= dady7:gsub('W','𝘞')
dady7= dady7:gsub('e','𝘌')
dady7= dady7:gsub('E','𝘌')
dady7= dady7:gsub('r','𝘙')
dady7= dady7:gsub('R','𝘙')
dady7= dady7:gsub('t','𝘛')
dady7= dady7:gsub('T','𝘛')
dady7= dady7:gsub('y','𝘠')
dady7= dady7:gsub('Y','𝘠')
dady7= dady7:gsub('u','𝘜')
dady7= dady7:gsub('U','𝘜')
dady7= dady7:gsub('i','𝘐')
dady7= dady7:gsub('I','𝘐')
dady7= dady7:gsub('o','𝘖')
dady7= dady7:gsub('O','𝘖')
dady7= dady7:gsub('p','𝘗')
dady7= dady7:gsub('P','𝘗')
dady7= dady7:gsub('a','𝘈')
dady7= dady7:gsub('A','𝘈')
dady7= dady7:gsub('s','𝘚')
dady7= dady7:gsub('S','𝘚')
dady7= dady7:gsub('d','𝘋')
dady7= dady7:gsub('D','𝘋')
dady7= dady7:gsub('f','𝘍')
dady7= dady7:gsub('F','𝘍')
dady7= dady7:gsub('g','𝘎')
dady7= dady7:gsub('G','𝘎')
dady7= dady7:gsub('h','𝘏')
dady7= dady7:gsub('H','𝘏')
dady7= dady7:gsub('j','𝘑')
dady7= dady7:gsub('J','𝘑')
dady7= dady7:gsub('k','𝘒')
dady7= dady7:gsub('K','𝘒')
dady7= dady7:gsub('L','𝘓')
dady7= dady7:gsub('l','𝘓')
dady7= dady7:gsub('z','𝘡')
dady7= dady7:gsub('Z','𝘡')
dady7= dady7:gsub('x','𝘟')
dady7= dady7:gsub('X','𝘟')
dady7= dady7:gsub('c','𝘊')
dady7= dady7:gsub('C','𝘊')
dady7= dady7:gsub('v','𝘝')
dady7= dady7:gsub('V','𝘝')
dady7= dady7:gsub('b','𝘉')
dady7= dady7:gsub('B','𝘉')
dady7= dady7:gsub('n','𝘕')
dady7= dady7:gsub('N','𝘕')
dady7= dady7:gsub('m','𝘔')
dady7= dady7:gsub('M','𝘔')



local dady8= Text:gsub('ض','ض');
dady8= dady8:gsub('ص','صہٰ')
dady8= dady8:gsub('ث','ثہٰـ')
dady8= dady8:gsub('ق','قہٰ')
dady8= dady8:gsub('ف','فہٰ')
dady8= dady8:gsub('غ','غـْ')
dady8= dady8:gsub('ع','ع')
dady8= dady8:gsub('ه','هٰہٰٖ')
dady8= dady8:gsub('خ','خخَـ')
dady8= dady8:gsub('ح','حہٰ')
dady8= dady8:gsub('ج','ججہٰ')
dady8= dady8:gsub('د','دَ')
dady8= dady8:gsub('ذ','ذّ')
dady8= dady8:gsub('ش','ششہٰ')
dady8= dady8:gsub('س','سہٰ')
dady8= dady8:gsub('ي','يٰ')
dady8= dady8:gsub('ب','بٰٰ')
dady8= dady8:gsub('ل','لہٰ')
dady8= dady8:gsub('ا','آ')
dady8= dady8:gsub('ت','تہٰ')
dady8= dady8:gsub('ن','نہٰ')
dady8= dady8:gsub('م','مہٰ')
dady8= dady8:gsub('ك','ككہٰ')
dady8= dady8:gsub('ط','طہٰ')
dady8= dady8:gsub('ئ',' ْئٰ')
dady8= dady8:gsub('ء','ء')
dady8= dady8:gsub('ؤ','ؤؤَ')
dady8= dady8:gsub('ر','رَ')
dady8= dady8:gsub('لا','لہٰا')
dady8= dady8:gsub('ى','ىہٰ')
dady8= dady8:gsub('ة','ة')
dady8= dady8:gsub('و','ہٰو')
dady8= dady8:gsub('ز','ز')
dady8= dady8:gsub('ظ','ظہٰ')
dady8= dady8:gsub('q','𝚀')
dady8= dady8:gsub('Q','𝚀')
dady8= dady8:gsub('w','𝚆')
dady8= dady8:gsub('W','𝚆')
dady8= dady8:gsub('e','𝙴')
dady8= dady8:gsub('E','𝙴')
dady8= dady8:gsub('r','𝚁')
dady8= dady8:gsub('R','𝚁')
dady8= dady8:gsub('t','𝚃')
dady8= dady8:gsub('T','𝚃')
dady8= dady8:gsub('y','𝚈')
dady8= dady8:gsub('Y','𝚈')
dady8= dady8:gsub('u','𝚄')
dady8= dady8:gsub('U','𝚄')
dady8= dady8:gsub('i','𝙸')
dady8= dady8:gsub('I','𝙸')
dady8= dady8:gsub('o','𝙾')
dady8= dady8:gsub('O','𝙾')
dady8= dady8:gsub('p','𝙿')
dady8= dady8:gsub('P','𝙿')
dady8= dady8:gsub('a','𝙰')
dady8= dady8:gsub('A','𝙰')
dady8= dady8:gsub('s','𝚂')
dady8= dady8:gsub('S','𝚂')
dady8= dady8:gsub('d','𝙳')
dady8= dady8:gsub('D','𝙳')
dady8= dady8:gsub('f','𝙵')
dady8= dady8:gsub('F','𝙵')
dady8= dady8:gsub('g','𝙶')
dady8= dady8:gsub('G','𝙶')
dady8= dady8:gsub('h','𝙷')
dady8= dady8:gsub('H','𝙷')
dady8= dady8:gsub('j','𝙹')
dady8= dady8:gsub('J','𝙹')
dady8= dady8:gsub('k','𝙺')
dady8= dady8:gsub('K','𝙺')
dady8= dady8:gsub('L','𝙻')
dady8= dady8:gsub('l','𝙻')
dady8= dady8:gsub('z','𝚉')
dady8= dady8:gsub('Z','𝚉')
dady8= dady8:gsub('x','𝚇')
dady8= dady8:gsub('X','𝚇')
dady8= dady8:gsub('c','𝙲')
dady8= dady8:gsub('C','𝙲')
dady8= dady8:gsub('v','𝚅')
dady8= dady8:gsub('V','𝚅')
dady8= dady8:gsub('b','𝙱')
dady8= dady8:gsub('B','𝙱')
dady8= dady8:gsub('n','𝙽')
dady8= dady8:gsub('N','𝙽')
dady8= dady8:gsub('m','𝙼')
dady8= dady8:gsub('M','𝙼')



local dady9= Text:gsub('ض','ض')
dady9= dady9:gsub('ص','ص')
dady9= dady9:gsub('ث','ث')
dady9= dady9:gsub('ق','قٌ')
dady9= dady9:gsub('ف','فُ')
dady9= dady9:gsub('غ','غ')
dady9= dady9:gsub('ع','عٍ')
dady9= dady9:gsub('ه','هـ')
dady9= dady9:gsub('خ','خـ')
dady9= dady9:gsub('ح','حٍ')
dady9= dady9:gsub('ج','جٍ')
dady9= dady9:gsub('د','دِ')
dady9= dady9:gsub('ذ','ذَ')
dady9= dady9:gsub('ش','شُ')
dady9= dady9:gsub('س','س')
dady9= dady9:gsub('ي','ي')
dady9= dady9:gsub('ب','بَ')
dady9= dady9:gsub('ل','لُِ')
dady9= dady9:gsub('ا','آ')
dady9= dady9:gsub('ت','ت')
dady9= dady9:gsub('ن','ن')
dady9= dady9:gsub('م','م')
dady9= dady9:gsub('ك','ڪ')
dady9= dady9:gsub('ط','طُ')
dady9= dady9:gsub('ئ','ئ ْٰ')
dady9= dady9:gsub('ء','ء')
dady9= dady9:gsub('ؤ','ؤ')
dady9= dady9:gsub('ر','ر')
dady9= dady9:gsub('لا','لُِآ')
dady9= dady9:gsub('ى','ىْ')
dady9= dady9:gsub('ة','ة')
dady9= dady9:gsub('و','وو')
dady9= dady9:gsub('ز','ز')
dady9= dady9:gsub('ظ','ظهُ')
dady9= dady9:gsub('q','ℚ')
dady9= dady9:gsub('Q','ℚ')
dady9= dady9:gsub('w','𝕎')
dady9= dady9:gsub('W','𝕎')
dady9= dady9:gsub('e','𝔼')
dady9= dady9:gsub('E','𝔼')
dady9= dady9:gsub('r','ℝ')
dady9= dady9:gsub('R','ℝ')
dady9= dady9:gsub('t','𝕋')
dady9= dady9:gsub('T','𝕋')
dady9= dady9:gsub('y','𝕐')
dady9= dady9:gsub('Y','𝕐')
dady9= dady9:gsub('u','𝕌')
dady9= dady9:gsub('U','𝕌')
dady9= dady9:gsub('i','𝕀')
dady9= dady9:gsub('I','𝕀')
dady9= dady9:gsub('o','𝕆')
dady9= dady9:gsub('O','𝕆')
dady9= dady9:gsub('p','ℙ')
dady9= dady9:gsub('P','ℙ')
dady9= dady9:gsub('a','𝔸')
dady9= dady9:gsub('A','𝔸')
dady9= dady9:gsub('s','𝕊')
dady9= dady9:gsub('S','𝕊')
dady9= dady9:gsub('d','𝔻')
dady9= dady9:gsub('D','𝔻')
dady9= dady9:gsub('f','𝔽')
dady9= dady9:gsub('F','𝔽')
dady9= dady9:gsub('g','𝔾')
dady9= dady9:gsub('G','𝔾')
dady9= dady9:gsub('h','ℍ')
dady9= dady9:gsub('H','ℍ')
dady9= dady9:gsub('j','𝕁')
dady9= dady9:gsub('J','𝕁')
dady9= dady9:gsub('k','𝕂')
dady9= dady9:gsub('K','𝕂')
dady9= dady9:gsub('L','𝕃')
dady9= dady9:gsub('l','𝕃')
dady9= dady9:gsub('z','ℤ')
dady9= dady9:gsub('Z','ℤ')
dady9= dady9:gsub('x','𝕏')
dady9= dady9:gsub('X','𝕏')
dady9= dady9:gsub('c','ℂ')
dady9= dady9:gsub('C','ℂ')
dady9= dady9:gsub('v','𝕍')
dady9= dady9:gsub('V','𝕍')
dady9= dady9:gsub('b','𝔹')
dady9= dady9:gsub('B','𝔹')
dady9= dady9:gsub('n','ℕ')
dady9= dady9:gsub('N','ℕ')
dady9= dady9:gsub('m','𝕄')
dady9= dady9:gsub('M','𝕄')


local Text_dadya = "1- `"..dady..EmojeS[math.random(#EmojeS)]
.."`\n\n2- `"..dady2..EmojeS[math.random(#EmojeS)]
.."`\n\n3- `"..dady3..EmojeS[math.random(#EmojeS)]
.."`\n\n4- `"..dady4..EmojeS[math.random(#EmojeS)]
.."`\n\n5- `"..dady5..EmojeS[math.random(#EmojeS)]
.."`\n\n6- `"..dady6..EmojeS[math.random(#EmojeS)]
.."`\n\n7- `"..dady7..EmojeS[math.random(#EmojeS)]
.."`\n\n8- `"..dady8..Emoje[math.random(#Emoje)]
.."`\n\n9- `"..dady9..Emoje[math.random(#Emoje)]
.."`\n\n10- `"..dady5..Emoje[math.random(#Emoje)]
Text_dadya = Text_dadya.."`\n\n| اضغـط علـي الاسـم ليتـم النـسخ  \n★"
sendMsg(msg.chat_id_,msg.id_,Text_dadya)
return false
end



end

return {
dady = {
"^(زخرفه)$"
 },
 idady = dadya,
 ddady = TextRes,
 }
 
 

--[[
███████▀ │dady ﹏ @KGT_dady
│تم تطوير وبرمجة السورس من قبل دادي .
│@kgtbm
#-------------------------------------------------------------------
]]
